export const builtInWindowArrangements = {
  CLASSIC: [
    {
      id: "WORKSPACE",
      top: "32px",
      left: "146px",
      width: "600px",
      height: "600px",
    },
    {
      id: "COLOURPALLET",
      top: "296px",
      left: "749px",
      width: "180px",
      height: "284px",
    },
    {
      id: "TOOLBAR",
      top: "32px",
      left: "1px",
      width: "142px",
      height: "600px",
    },
    {
      id: "PREVIEW",
      top: "32px",
      left: "932px",
      width: "180px",
      height: "200px",
    },
    {
      id: "ANIMATIONPREVIEW",
      top: "32px",
      left: "1115px",
      width: "180px",
      height: "200px",
    },
    {
      id: "ANIMATIONTOOLS",
      top: "585px",
      left: "749px",
      width: "180px",
      height: "42px",
    },
    {
      id: "TOOLOPTIONS",
      top: "32px",
      left: "749px",
      width: "180px",
      height: "260px",
    },
    {
      id: "LAYERS",
      top: "235px",
      left: "932px",
      width: "180px",
      height: "396px",
    },
    {
      id: "FRAMES",
      top: "235px",
      left: "1115px",
      width: "181px",
      height: "397px",
    },
    { id: "DEBUG", top: "636px", left: "4px", width: "500px", height: "120px" },
    {
      id: "OPENGALLERY",
      top: "200px",
      left: "200px",
      width: "800px",
      height: "600px",
    },
    {
      id: "PIXELBRUSH",
      top: "636px",
      left: "508px",
      width: "500px",
      height: "120px",
    },
  ],
  NEOCLASSIC: [
    {
      id: "WORKSPACE",
      top: "32px",
      left: "328px",
      width: "600px",
      height: "600px",
    },
    {
      id: "COLOURPALLET",
      top: "348px",
      left: "145px",
      width: "180px",
      height: "284px",
    },
    {
      id: "TOOLBAR",
      top: "32px",
      left: "1px",
      width: "142px",
      height: "600px",
    },
    {
      id: "PREVIEW",
      top: "32px",
      left: "932px",
      width: "180px",
      height: "200px",
    },
    {
      id: "ANIMATIONPREVIEW",
      top: "32px",
      left: "1115px",
      width: "180px",
      height: "200px",
    },
    {
      id: "ANIMATIONTOOLS",
      top: "717px",
      left: "1116px",
      width: "180px",
      height: "42px",
    },
    {
      id: "TOOLOPTIONS",
      top: "33px",
      left: "145px",
      width: "181px",
      height: "312px",
    },
    {
      id: "LAYERS",
      top: "235px",
      left: "932px",
      width: "179px",
      height: "523px",
    },
    {
      id: "FRAMES",
      top: "235px",
      left: "1115px",
      width: "180px",
      height: "477px",
    },
    { id: "DEBUG", top: "636px", left: "4px", width: "500px", height: "120px" },
    {
      id: "PIXELBRUSH",
      top: "636px",
      left: "508px",
      width: "421px",
      height: "121px",
    },
    {
      id: "OPENGALLERY",
      top: "200px",
      left: "200px",
      width: "800px",
      height: "600px",
    },
    {
      id: "GIFDISPLAY",
      top: "300px",
      left: "400px",
      width: "200px",
      height: "200px",
    },
  ],
  WIDE: [
    {
      id: "WORKSPACE",
      top: "131px",
      left: "5px",
      width: "925px",
      height: "537px",
    },
    {
      id: "COLOURPALLET",
      top: "533px",
      left: "932px",
      width: "180px",
      height: "267px",
    },
    {
      id: "TOOLBAR",
      top: "33px",
      left: "2px",
      width: "1113px",
      height: "96px",
    },
    {
      id: "PREVIEW",
      top: "131px",
      left: "933px",
      width: "180px",
      height: "200px",
    },
    {
      id: "ANIMATIONPREVIEW",
      top: "32px",
      left: "1115px",
      width: "180px",
      height: "200px",
    },
    {
      id: "TOOLOPTIONS",
      top: "333px",
      left: "932px",
      width: "181px",
      height: "197px",
    },
    {
      id: "DEBUG",
      top: "671px",
      left: "5px",
      width: "510px",
      height: "116px",
    },
    {
      id: "OPENGALLERY",
      top: "200px",
      left: "200px",
      width: "800px",
      height: "600px",
    },
  ],
  TILECREATOR: [
    {
      id: "WORKSPACE",
      top: "32px",
      left: "146px",
      width: "600px",
      height: "600px",
    },
    {
      id: "COLOURPALLET",
      top: "296px",
      left: "749px",
      width: "180px",
      height: "284px",
    },
    {
      id: "TOOLBAR",
      top: "32px",
      left: "1px",
      width: "142px",
      height: "600px",
    },
    {
      id: "PREVIEW",
      top: "32px",
      left: "932px",
      width: "400px",
      height: "394px",
    },
    {
      id: "ANIMATIONPREVIEW",
      top: "430px",
      left: "932px",
      width: "175px",
      height: "185px",
    },
    {
      id: "ANIMATIONTOOLS",
      top: "585px",
      left: "749px",
      width: "180px",
      height: "42px",
    },
    {
      id: "TOOLOPTIONS",
      top: "635px",
      left: "508px",
      width: "188px",
      height: "121px",
    },
    {
      id: "LAYERS",
      top: "32px",
      left: "748px",
      width: "181px",
      height: "262px",
    },
    {
      id: "FRAMES",
      top: "430px",
      left: "1112px",
      width: "171px",
      height: "319px",
    },
    { id: "DEBUG", top: "636px", left: "4px", width: "500px", height: "120px" },
    {
      id: "OPENGALLERY",
      top: "200px",
      left: "200px",
      width: "800px",
      height: "600px",
    },
  ],
};
